# Generated by Django 4.1.1 on 2023-02-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ese nombre de usuario ya existe.'}, max_length=150, unique=True, verbose_name='username'),
        ),
    ]
